import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Identifying Personality Disorders Test',
  description: 'Generated by create next app',
};

export default function IdentifyingPersonalityDisordersTest() {
  return <div>Identifying Personality Disorders Test</div>;
}
