import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './Components/Header';
import Footer from './Components/Footer';
import Container from './Components/Container';
import Providers from '@/GlobalRedux/Provider';
import MainContainer from './Components/MainContainer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Elena Halashova | Psychologist',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <MainContainer>
            <Header />
            <Container>
              {children}
              <Footer />
            </Container>
          </MainContainer>
        </Providers>
      </body>
    </html>
  );
}
